import { RELEASE_VERSION } from "../release-version.ts";

export function authenticationGuideBody(origin: string): string {
  return [
    "# cfKanban auth.md",
    "",
    `Release / 发行版本: ${RELEASE_VERSION}`,
    "",
    "## English",
    "",
    "Audience: Agents and API clients using this cfKanban instance on behalf of an authorized user. People and Agents use the same Principal identity and project authorization rules.",
    "",
    "### Authenticate with an existing credential",
    "",
    "The API accepts a long-lived opaque `cfk_v1` Credential in the HTTP header `Authorization: Bearer <credential>`. `<credential>` is a placeholder. This is bearer authentication, not OAuth; there is no authorization server, token exchange, ID-JAG, or anonymous registration endpoint.",
    "",
    `Send authenticated requests only to this verified instance origin: \`${origin}\`. Use the installed cfKanban CLI or Skills: their security runtime reads the current Credential from private local storage and sends the header internally. Never paste a Credential into chat, a webpage, a URL, command arguments, environment variables, or an \`.env\` file. Do not request or return its plaintext.`,
    "",
    `- [GET /api/v1/me](${origin}/api/v1/me): verify the current Principal and returned current authorization information.`,
    `- [GET /api/v1/meta](${origin}/api/v1/meta): read authenticated instance versions and capabilities.`,
    "",
    "No separate API login request is needed. Authentication identifies a Principal; it does not grant access to arbitrary Projects. Project roles (`reader` or `writer`) and management permissions are checked separately on every operation. Do not choose an identity or infer permission from a display name.",
    "",
    "### Obtain or recover access",
    "",
    "Install compatible CLI/Skills from the official stable installation guide below, then use one of the existing, explicitly authorized joining workflows:",
    "",
    `1. **Ordinary Project invitation:** obtain a valid invitation from an authorized administrator. The provisioning endpoint is [POST /api/v1/invitations/redeem](${origin}/api/v1/invitations/redeem), with \`redeem_as: new_principal\` for first use or \`current_principal\` for a usable existing identity. The invitation specifies the Project(s) and roles it grants.`,
    `2. **Enabled Public Join:** choose one public Project and an explicit \`reader\` or \`writer\` role. The provisioning endpoint is \`POST ${origin}/api/v1/public-joins/{public_id}/redeem\`, where \`{public_id}\` identifies that enabled public entry. It also supports \`new_principal\` or \`current_principal\`; existing-identity mode requires authentication.`,
    "",
    "For `new_principal`, both APIs require `display_name` and `new_credential_token`; invitation redemption also requires `invite_code`, and Public Join requires `role`. Use the public CLI `join invite` or `join public` workflow, or the corresponding Skill. The Skill uses internal `credential prepare`, `invite redeem`, and `public-join redeem` helpers; these are not public CLI command names. The security runtime generates and privately stores a pending Credential, injects it internally, verifies `/api/v1/me`, then retains it as the local current identity. Both joining methods grant their selected Project access: there is no separate registration that creates a Credential with zero Project permissions. Joining does not grant an entire Workspace or administrator status.",
    "",
    "Reading this document or opening a joining link does not authorize redemption. Obtain the user's approval for the specific identity, target, and role; passive discovery must not POST or create an account. Writes use an `Idempotency-Key`; on timeout or an uncertain response, preserve the original request, key, and pending state and let the dedicated workflow verify or resume it.",
    "",
    "For a lost participant Credential, ask the Owner for recovery of the same Principal through a recovery invitation (`redeem_as: recovery`), rather than registering again. Credential revocation and Owner device connection, rotation, or total recovery use their existing dedicated workflows. Recovery preserves identity and is not registration.",
    "",
    "The Web interface uses an existing Passkey or an Agent's secure Browser Launch. It never requires pasting the API Credential; browser sessions and Passkeys do not grant additional Project permissions.",
    "",
    `- [Joining and signing in](${origin}/docs/en/usage/access)`,
    `- [Devices, revocation, and identity recovery](${origin}/docs/en/administration/devices)`,
    `- [Deployment and total Owner recovery](${origin}/docs/en/deployment/recovery)`,
    "- [Official stable installation guide](https://github.com/breakstring/cfKanban/releases/latest/download/install.md)",
    "",
    "## 简体中文",
    "",
    "适用对象：代表已获授权用户访问本实例的 Agent 和 API 客户端。人和 Agent 使用相同的 Principal 身份及项目授权规则。",
    "",
    "### 使用已有凭据鉴权",
    "",
    "API 接受长期、不透明的 `cfk_v1` Credential，通过 HTTP 请求头 `Authorization: Bearer <credential>` 鉴权；`<credential>` 只是占位符。这是 Bearer 鉴权，不是 OAuth；本实例不提供授权服务器、Token 交换、ID-JAG 或匿名注册接口。",
    "",
    `鉴权请求只能发往已核验的本实例 origin：\`${origin}\`。使用已安装的 cfKanban CLI 或技能，由安全 runtime 从本地私有状态读取当前凭据，并在内部添加请求头。不要将凭据粘贴到聊天、网页、URL、命令参数、环境变量或 \`.env\` 文件，不要索取或输出明文凭据。`,
    "",
    `- [GET /api/v1/me](${origin}/api/v1/me)：核验当前 Principal 及响应中的实际授权信息。`,
    `- [GET /api/v1/meta](${origin}/api/v1/meta)：鉴权后读取实例版本和能力。`,
    "",
    "API 无需另行调用登录接口。鉴权只确认身份，不意味着可访问任意项目。项目角色（`reader` 或 `writer`）及管理权限在每次操作时独立检查；不能根据显示名称选择身份或推断权限。",
    "",
    "### 获取或恢复访问权限",
    "",
    "通过下方官方正式版引导安装兼容的 CLI / 技能，然后使用已有、经过明确授权的加入流程：",
    "",
    `1. **普通项目邀请：** 从有权管理员获取有效邀请。加入接口为 [POST /api/v1/invitations/redeem](${origin}/api/v1/invitations/redeem)；首次使用选择 \`redeem_as: new_principal\`，有可用身份时选择 \`current_principal\`。邀请明确授予哪些项目及角色。`,
    `2. **已开启的公开加入：** 选择一个公开项目，并明确选择 \`reader\` 或 \`writer\`。加入接口为 \`POST ${origin}/api/v1/public-joins/{public_id}/redeem\`，其中 \`{public_id}\` 是该公开入口的标识。它同样支持 \`new_principal\` 或 \`current_principal\`；使用已有身份时需要鉴权。`,
    "",
    "两种接口在 `new_principal` 模式下都需要 `display_name` 和 `new_credential_token`；邀请兑换还需要 `invite_code`，公开加入需要 `role`。使用公共 CLI 的 `join invite` 或 `join public` 流程，或对应技能。技能内部使用 `credential prepare`、`invite redeem` 和 `public-join redeem` helper，这些不是公共 CLI 命令名。安全 runtime 生成并私有保存待验证凭据，在内部注入请求，核验 `/api/v1/me` 后保存为本地当前身份。这两种加入方式都会授予选定项目的权限，不提供独立注册后获得零项目权限凭据的接口；加入不会授予整个工作区或管理员身份。",
    "",
    "读取本文或打开加入链接不代表授权兑换。应先取得用户对具体身份、目标及角色的批准；被动发现不得发起 POST 或创建账号。写入使用 `Idempotency-Key`；发生超时或结果不确定时，保留原请求、原键及待验证状态，由专用流程核实或恢复执行。",
    "",
    "参与者凭据丢失时，联系 Owner 通过恢复邀请（`redeem_as: recovery`）恢复同一个 Principal，不要重新注册。凭据撤销、Owner 设备接入、轮换或全失恢复使用已有专用流程；恢复保留原身份，不是注册。",
    "",
    "网页使用已登记的 Passkey 或 Agent 的安全 Browser Launch，不要求粘贴 API 凭据；网页会话和 Passkey 不会增加项目权限。",
    "",
    `- [加入与登录](${origin}/docs/zh-CN/usage/access)`,
    `- [设备、撤销与身份恢复](${origin}/docs/zh-CN/administration/devices)`,
    `- [部署与 Owner 全失恢复](${origin}/docs/zh-CN/deployment/recovery)`,
    "- [官方正式版安装引导](https://github.com/breakstring/cfKanban/releases/latest/download/install.zh-CN.md)",
    "",
    "## API and Skill discovery / API 与技能发现",
    "",
    `- [OpenAPI: request schemas and supported methods / 请求结构与支持的方法](${origin}/openapi.json)`,
    `- [API Catalog](${origin}/.well-known/api-catalog)`,
    `- [Skills Discovery / 技能发现](${origin}/.well-known/agent-skills/index.json)`,
    `- [Public documentation index / 公开文档索引](${origin}/llms.txt)`,
    "",
  ].join("\n");
}
