import contract from '../../../contracts/openapi.json' with { type: 'json' };

// Public nouns/actions stay independent from the internal Skill helper names.
const names = {
  getMeta: 'instance info', getMe: 'profile show', updateMe: 'profile update',
  getNotificationPreferences: 'notification preferences', updateNotificationPreferences: 'notification configure', listMyNotifications: 'notification list', acknowledgeNotification: 'notification acknowledge',
  listInstanceNotifications: 'admin notification list', publishNotification: 'admin notification publish', withdrawNotification: 'admin notification withdraw', listEvents: 'event list',
  listWorkspaces: 'workspace list', createWorkspace: 'workspace create', getWorkspace: 'workspace show', updateWorkspace: 'workspace update', deleteWorkspace: 'workspace archive', previewWorkspacePurge: 'workspace purge-preview', purgeWorkspace: 'workspace purge', restoreWorkspace: 'workspace restore',
  listProjects: 'project list', createProject: 'project create', getProject: 'project show', updateProject: 'project update', deleteProject: 'project archive', previewProjectPurge: 'project purge-preview', purgeProject: 'project purge', restoreProject: 'project restore',
  findProjectAssignee: 'project assignee list', listProjectStatuses: 'project status list', updateProjectStatusName: 'project status rename',
  listWorkspaceAdministratorCandidates: 'workspace administrator candidates', listWorkspaceAdministrators: 'workspace administrator list', createWorkspaceAdministrator: 'workspace administrator add', revokeWorkspaceAdministrator: 'workspace administrator remove',
  listProjectAdministratorCandidates: 'project administrator candidates', listProjectAdministrators: 'project administrator list', createProjectAdministrator: 'project administrator add', revokeProjectAdministrator: 'project administrator remove', listProjectMembers: 'project member list', listProjectMemberCandidates: 'project member candidates',
  listIssues: 'issue list', listIssueCandidates: 'issue candidates', listProjectIssues: 'project issue list', createIssue: 'issue create', countProjectIssues: 'issue counts', getIssue: 'issue show', getIssueReference: 'issue reference', updateIssue: 'issue update', deleteIssue: 'issue delete', restoreIssue: 'issue restore', getIssueContext: 'issue context', assignIssueToMe: 'issue assign-me', reportIssueBlocked: 'issue block', clearIssueBlocked: 'issue unblock', completeIssue: 'issue complete', addIssueLabel: 'issue label add', removeIssueLabel: 'issue label remove',
  listAttachments: 'attachment list', getAttachment: 'attachment show', deleteAttachment: 'attachment delete', restoreAttachment: 'attachment restore', listComments: 'comment list', createComment: 'comment create', getComment: 'comment show', deleteComment: 'comment delete', restoreComment: 'comment restore',
  listLabels: 'label list', createLabel: 'label create', getLabel: 'label show', updateLabel: 'label update', deleteLabel: 'label delete', restoreLabel: 'label restore', listIssueRelations: 'relation list', createIssueRelation: 'relation create', getRelation: 'relation show', deleteRelation: 'relation delete', restoreRelation: 'relation restore',
  listInvitations: 'invite list', getInvitation: 'invite show', revokeInvitation: 'invite revoke', listPrincipals: 'admin principal list', getPrincipal: 'admin principal show', listPrincipalCredentials: 'admin credential list', revokeCredential: 'admin credential revoke', renameOwnerDeviceCredential: 'owner device rename',
  getInstanceOrigin: 'admin origin show', updateInstanceOrigin: 'admin origin update', listProjectGrants: 'grant list', createProjectGrant: 'grant create', getProjectGrant: 'grant show', updateProjectGrant: 'grant update', revokeProjectGrant: 'grant revoke', listAuditEvents: 'admin audit list', listMyPasskeys: 'passkey list', revokeMyPasskey: 'passkey revoke', revokePrincipalPasskey: 'admin passkey revoke',
  listPublicProjects: 'join projects', getPublicJoinPolicy: 'admin public-join show', enablePublicJoin: 'admin public-join enable', disablePublicJoin: 'admin public-join disable', getProjectResourceLimits: 'admin limits show', updateProjectResourceLimits: 'admin limits update', getHomepageSettings: 'admin homepage show', updateHomepageSettings: 'admin homepage update', getAttachmentSettings: 'admin attachment-capacity show', updateAttachmentSettings: 'admin attachment-capacity update', getUsage: 'admin usage snapshot', refreshUsage: 'admin usage show', getRateLimitSettings: 'admin rate-limits show',
};
function resolve(value) {
  if (!value || typeof value !== 'object') return value;
  if (value.$ref) return resolve(value.$ref.split('/').slice(1).reduce((current, key) => current[key], contract));
  if (Array.isArray(value)) return value.map(resolve);
  return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, resolve(entry)]));
}
export const API_COMMANDS = Object.entries(contract.paths).flatMap(([apiPath, methods]) => Object.entries(methods).flatMap(([method, operation]) => {
  if (!names[operation.operationId]) return [];
  return [{ name: names[operation.operationId], operation: operation.operationId, write_contract:operation['x-cfkanban-write-contract'], method: method.toUpperCase(), apiPath, parameters: resolve(operation.parameters ?? []), body: resolve(operation.requestBody?.content?.['application/json']?.schema ?? null), description: operation.summary ?? names[operation.operationId], effect: method === 'get' ? 'read' : 'write' }];
}));

const helpers = [
  ['connection list', 'state inspect', []], ['connection add', 'state put-instance', ['instanceId','trustedApiOrigin','originVersion','persistenceConfirmed']],
  ['connection resolve','web resolve',['instanceId','origin','repoRoot']],
  ['scope inspect', 'scope inspect-directory', ['directory']], ['scope show', 'scope read', ['repoRoot']], ['scope associate', 'scope merge', ['repoRoot','targets']], ['scope resolve', 'scope resolve', ['explicitTargets','repoTargets','validTargets','allowUnfiltered']],
  ['attachment upload', 'attachment upload', ['instanceId','identifier','filePath','idempotencyKey','attachmentId','firstAttemptAt']], ['attachment download', 'attachment download', ['instanceId','attachmentId','outputPath']],
  ['invite create', 'invite create', ['instanceId','body','idempotencyKey','delivery','sensitiveOutputAcknowledgement']],
  ['owner device prepare', 'owner-device prepare', ['instanceId','apiOrigin','ownerPrincipalId','deviceName','operationId','idempotencyKey','expiresInSeconds','persistenceConfirmed','replaceCurrent','expectedCurrentPrincipalId','expectedCurrentCredentialId']], ['owner device request', 'owner-device request', ['instanceId']], ['owner device approve', 'owner-device approve', ['instanceId','request']], ['owner device verify', 'owner-device verify', ['instanceId']], ['owner device list', 'owner-device list', ['instanceId','cursor']], ['owner device revoke', 'owner-device revoke', ['instanceId','credentialId','idempotencyKey']], ['owner device restore-previous', 'owner-device restore-previous', ['instanceId','expectedCurrentPrincipalId','expectedCurrentCredentialId']],
  ['web preflight', 'web preflight', ['delivery']], ['web open', 'web open', ['instanceId','mode','directory','workspace_id','project_id','target','delivery','idempotencyKey','sensitiveOutputAcknowledgement']],
  ['deploy capabilities', 'capabilities', []], ['deploy release discover', 'release discover', ['version','selectionMode']], ['deploy release verify', 'release verify', ['releasePointerPath','manifestPath','artifactFiles']], ['deploy release continuity', 'release continuity', ['currentReceipt','targetManifest']],
  ['deploy runtime resolve', 'runtime resolve-wrangler', ['explicitPath','requiredRange']], ['deploy runtime plan', 'runtime plan-install', ['taskId','npmExecutable','wranglerVersion']], ['deploy runtime install', 'runtime install', ['plan','authorizedTaskId','authorizedPlanDigest']],
  ['deploy auth resolve', 'runtime resolve-cloudflare-auth', ['wranglerExecutable','contextDirectory','selectedProfile']], ['deploy auth inspect', 'runtime inspect-cloudflare-auth', ['wranglerExecutable','profileName','attachmentStorage']], ['deploy auth plan', 'runtime plan-cloudflare-auth', ['taskId','mode','preflight','allowExistingProfile','attachmentStorage']],
  ['deploy account verify', 'runtime wrangler-account-readback', ['wranglerExecutable','accountId','cloudflareProfile','contextDirectory']],
  ['deploy database inspect','runtime d1-resource-readback',['wranglerExecutable','accountId','cloudflareProfile','contextDirectory','d1Name']],
  ['deploy database restore-point','runtime d1-restore-point-readback',['wranglerExecutable','accountId','cloudflareProfile','contextDirectory','d1Name']],
  ['deploy worker inspect','runtime worker-resource-readback',['wranglerExecutable','accountId','cloudflareProfile','contextDirectory','workerName']],
  ['deploy worker version','runtime worker-version-readback',['wranglerExecutable','accountId','cloudflareProfile','contextDirectory','workerName','versionId']],
  ['deploy storage inspect','runtime r2-storage-readback',['wranglerExecutable','accountId','cloudflareProfile','contextDirectory','bucketName','instanceId']],
  ['deploy skill plan', 'plan skill-update', ['taskId','current','target','installRoot']], ['deploy skill install', 'release install-skill-bundle', ['bundlePath','version','expectedSha256','publisher','source']], ['deploy service cache', 'release install-service-bundle', ['bundlePath','version','expectedSha256','publisher','source']],
  ['deploy plan', 'plan strict-zero', ['taskId','accountId','accountLabel','cloudflareProfile','cloudflareAuthContextDirectory','ownerDisplayName','release','resourcePrefix','workerName','d1Name','instanceId','ownerPrincipalId','ownerCredentialId','operationId','preferredApiOrigin']], ['deploy upgrade plan', 'plan instance-upgrade', ['taskId','instanceId','operationId','cloudflare','resources','bindings','owner','current','target','migrations','restorePoint','allow_breaking_change','allow_unverified_current_source','attachments','usageAnalytics']],
  ['deploy plan compare','plan compare',['before','after']],
  ['deploy attach inspect', 'deployment inspect-existing', ['instanceId','accountId','workerName','d1Name','databaseId','apiOrigin','wranglerExecutable','cloudflareProfile','contextDirectory','baselineBundle','publisher']], ['deploy attach plan', 'plan deployment-attachment', ['taskId','instanceId','accountId','workerName','d1Name','databaseId','apiOrigin','wranglerExecutable','cloudflareProfile','contextDirectory','baselineBundle','publisher']],
  ['deploy recovery discover', 'owner-recovery discover', ['accountId','wranglerExecutable','cloudflareProfile','contextDirectory','workerNames']], ['deploy recovery inspect', 'owner-recovery inspect', ['instanceId','accountId','workerName','d1Name','databaseId','apiOrigin','wranglerExecutable','cloudflareProfile','contextDirectory']], ['deploy recovery plan', 'plan owner-recovery', ['taskId','instanceId','accountId','workerName','d1Name','databaseId','apiOrigin','wranglerExecutable','cloudflareProfile','contextDirectory']],
];
export const HELPER_COMMANDS = helpers.map(([name, helper, fields]) => ({ name, helper, fields, effect: /(?:show|list|inspect|resolve|discover|verify|continuity|snapshot|capabilities)$/.test(name) ? 'read' : /plan$/.test(name) ? 'plan' : 'write', description: name }));
export const WORKFLOW_COMMANDS = [
  ...['show','use','clear'].map(action=>({name:`context ${action}`,workflow:`context-${action}`,fields:['instanceId','workspace_id','project_id','directory','global'],required:[],effect:action==='show'?'read':'write'})),
  {name:'connection discover',workflow:'connection-discover',fields:['origin'],required:['origin'],effect:'read'},
  {name:'connection origin-check',helper:'origin rebind-check',fields:['instanceId'],effect:'read'},
  {name:'instance health',workflow:'instance-health',fields:['instanceId'],effect:'read'},
  {name:'instance contract',workflow:'instance-contract',fields:['instanceId'],effect:'read'},
  ...['status','install','rollback','uninstall'].map(action=>({name:`cli ${action}`,workflow:`cli-${action}`,fields:action==='rollback'?[]:['commandDirectory',...(action==='install'?['nodePath']:[])],effect:action==='status'?'read':'write'})),
  { name: 'join invite', workflow: 'join-invite', fields: ['instanceId','redeemAs','displayName','operationId','idempotencyKey','persistenceConfirmed'], sensitiveStdin: true, effect: 'write' },
  { name: 'join public', workflow: 'join-public', fields: ['instanceId','publicId','role','redeemAs','displayName','operationId','idempotencyKey','persistenceConfirmed'], effect: 'write' },
  { name: 'identity pending', helper: 'state inspect', fields: ['instanceId'], effect: 'read' },
  { name: 'identity verify', helper: 'credential verify-and-promote', fields: ['instanceId'], effect: 'write' },
  { name: 'identity discard-pending', helper: 'credential clear', fields: ['instanceId','committedStateKnownFalse'], effect: 'write' },
  { name: 'owner rotate', workflow: 'owner-rotate', fields: ['instanceId','operationId','idempotencyKey'], effect: 'write' },
  { name: 'board create', workflow: 'board-create', fields: ['instanceId','workspaceName','projectName','operationId'], effect: 'write' },
  { name: 'issue reopen', workflow: 'issue-reopen', fields: ['instanceId','identifier','statusKey','expectedVersion','operationId'], write_contract:'cas', effect: 'write' },
  { name: 'deploy auth apply', workflow: 'auth-apply', fields: ['plan','authorization','contextDirectory','accountId','persistenceConfirmed'], effect: 'write' },
  ...['apply','resume','upgrade apply','upgrade resume','attach apply','recovery apply'].map(name => ({ name: `deploy ${name}`, workflow: 'deploy-apply', fields: ['instanceId','operationId','taskId','plan','authorization','wranglerExecutable','serviceBundleRoot','releasePointerPath','manifestPath','artifactFiles','apiOrigin','currentReceiptPath'], effect: 'write' })),
  { name: 'operation show', workflow: 'operation-show', fields: ['instanceId','operationId'], effect: 'read' },
  { name: 'operation recover', workflow: 'operation-recover', fields: ['instanceId','operationId'], effect: 'write' },
];
const required = {
 'connection resolve':[], 'deploy plan compare':['before','after'],
 'connection add':['instanceId','trustedApiOrigin'], 'scope inspect':[], 'scope show':[], 'scope associate':['repoRoot','targets'], 'scope resolve':['validTargets'],
 'attachment upload':['instanceId','identifier','filePath'], 'attachment download':['instanceId','attachmentId','outputPath'], 'invite create':['instanceId','body'],
 'owner device prepare':['instanceId','apiOrigin','ownerPrincipalId','deviceName'], 'owner device approve':['instanceId','request'], 'owner device revoke':['instanceId','credentialId'], 'owner device restore-previous':['instanceId','expectedCurrentPrincipalId','expectedCurrentCredentialId'],
 'web open':['instanceId','target'], 'deploy release verify':['releasePointerPath','manifestPath','artifactFiles'], 'deploy release continuity':['currentReceipt','targetManifest'], 'deploy runtime resolve':['requiredRange'], 'deploy runtime plan':['taskId','npmExecutable','wranglerVersion'], 'deploy runtime install':['plan','authorizedTaskId','authorizedPlanDigest'],
 'deploy auth resolve':['wranglerExecutable','contextDirectory'], 'deploy auth inspect':['wranglerExecutable','profileName'], 'deploy auth plan':['taskId','mode','preflight'], 'deploy auth apply':['plan','authorization','contextDirectory'], 'deploy account verify':['wranglerExecutable','accountId'],
 'deploy database inspect':['wranglerExecutable','accountId','d1Name'], 'deploy database restore-point':['wranglerExecutable','accountId','d1Name'], 'deploy worker inspect':['wranglerExecutable','accountId','workerName'], 'deploy worker version':['wranglerExecutable','accountId','workerName','versionId'], 'deploy storage inspect':['wranglerExecutable','accountId','bucketName','instanceId'],
 'deploy skill plan':['taskId','current','target','installRoot'], 'deploy skill install':['bundlePath','version','expectedSha256','publisher','source'], 'deploy service cache':['bundlePath','version','expectedSha256','publisher','source'], 'deploy plan':['taskId','accountId','ownerDisplayName','release'], 'deploy upgrade plan':['taskId','instanceId','cloudflare','resources','bindings','owner','current','target','migrations','restorePoint'],
 'join invite':['instanceId','redeemAs'], 'join public':['instanceId','publicId','role','redeemAs'], 'identity discard-pending':['instanceId','committedStateKnownFalse'], 'board create':['instanceId','workspaceName','projectName'], 'issue reopen':['instanceId','identifier'], 'operation show':['instanceId','operationId'], 'operation recover':['instanceId','operationId'],
};
export const COMMANDS = Object.freeze([...API_COMMANDS, ...HELPER_COMMANDS, ...WORKFLOW_COMMANDS].map(command => Object.freeze({...command,effect:['owner device verify','connection origin-check'].includes(command.name)?'write':['owner device request','deploy database restore-point','deploy worker version'].includes(command.name)?'read':command.effect,required:command.required??required[command.name]??(command.workflow==='deploy-apply'?['plan','authorization']:command.fields?.includes('instanceId')?['instanceId']:[])})));
